{% set name = "conllu" %}
{% set version = "1.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "4b02cdc56b6d901b94ad4c456cefb782c22312a82d77e45889596bbaf87e6326" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python==2.7|>=3.4
    - pip
  run:
    - python==2.7|>=3.4

test:
  imports:
    - conllu

about:
  home: https://github.com/EmilStenstrom/conllu/
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: CoNLL-U Parser parses a CoNLL-U formatted string into a nested python dictionary
  description: CoNLL-U Parser parses a CoNLL-U formatted string into a nested python dictionary
  doc_url: https://github.com/EmilStenstrom/conllu/
  dev_url: https://github.com/EmilStenstrom/conllu/

extra:
  recipe-maintainers:
    - nelson-liu
