travis:
  secure:
    BINSTAR_TOKEN: dMiM3xU7XaUvn61zVeU4jmUM5wmSeOE151bnmkL8FNd6RY7L3pvJVm3PnGJtGDkJe/hHBz3ZRj3zJDjVJh9CINWc1Cw9llseOtN4NmnwMQsk6sJiuAj5CutoCLMRhYhzsleiQG7fo+8u/PsqwyO5XMdfU790STctalCLvrBCeVcjH02MVDnvVpRQoac0ku8znzi04p7ic1Akdlc3tW2eZyTs1eKsqv4pTgdp8ZBUzucAPlMYHFDNmdy67W0d0/p4hLV16VJRvMTwuK/dTeRS7qkINku6dqNJAVFUAcFanHinTullPqNe8/1SdRzejvXNTMY9zPcr73U9JLwekM2mNlpHCH5OzTjfmVJ0KJLD+enXArUauZbpNmD3i2v3Vf6ZBHj+cqH992w8lk62+xT9vhQjlayHcPTwWEUols3RXolpDwchALw7T6VKoa1Qr4PgNcQRr457hXwu+dk+r1ee5EvVfeRBqSmt4Bt2FdKzEsu3mRQT1BmILiNf+ilt6tt0bi3KZYkluohvu8RwNsbZ1hqBmrjYwHQAd6xtbQBhXBi3l76x6isPSBCv3tMCyoPsYA/DJQR2GSHn8nieZn1MMccZeOjkzgG/smOrT4nEwGk2U2fp7OyzxQMMaSoOtKG+8T2zaidGQmLBb+9CP9MVQcbByimi3bl0gMJnKYC84D8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
