travis:
  secure:
    BINSTAR_TOKEN: ZcVDOREoIUvxMK7YFaA5ZxLNafoAR2F6OGxSSHfGr6fGfxpshvvO6wnImttAjmOkT12+g86cE0FPvIFeiKnr0rYanmwhslFRWvFqGZ5YA3d0xGSre1YZrVr0HzBAmfdiDlYrwx06DeA+2j8W/V+4A9vNYbIio4sUsWOTK8Ljt4eN9mHy8WrHqSoMVhohgNBe9y3PSJaKvrGJMVSgL8/FRZb9jLBlDigxFKmhJE4NxaUy1JDCZrOItZu4qOuhvMRsu5Jud9P/mMR2LSoybYJCWnL1HRses6jX3f2ZS4RH94iN6pc+Hd0vHCgdcM2id5LtJHDAzztAjO4BlPUre6SW8JEztTL0dHCSmjIEAFHuNQnzoBkqokPritgjkYxevECIaiUEedtSRmup2VUrAx3K1zd83BizM0CaL69QfvZk11QQciNkO7UrL4tLnkpt6ZFYrH7S/hH0xLFh8WE9qLS5FXUb3UKa125P9/+zBFdGmwi/o0yYJD5mg+Tbw5f/jnmCx6wAf48c0RGwV72nnIfc+TQ/30KEb+TpVupL+uY9MYyZSCwdyrGLNHy5JQhQDxVdXOC55RLiEgReodxWte8LHzCuvEZuO+dYVFVq2XBxXMnX0Lva5hqZQaJ1788am4Dkh/8eWK0HtaFC2rvAaPmbWiwtffB3LchcGmhqhK1uYAA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
